import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID,randomBytes} from 'node:crypto';import {readFile} from 'node:fs/promises';import bcrypt from 'bcryptjs';import {chromium} from 'playwright-core';
const uri=new URL(process.env.TEST_MONGODB_URI!);uri.pathname='/browser_'+randomUUID().replaceAll('-','');process.env.MONGODB_URI=uri.toString();
const {db,seedRoles}=await import('../src/core.js');const {initializeDatabase}=await import('../src/database.js');const {app}=await import('../src/index.js');
test('real mobile and desktop browsers save offline, reload, export and sync the same account',async()=>{
  assert.ok(process.env.KHATA_CHROMIUM,'Set KHATA_CHROMIUM to a Chromium executable');await initializeDatabase(db);
  const tenant=await db.tenant.create({data:{name:'Browser Business'}});await db.subscription.create({data:{tenantId:tenant.id,plan:'Test',startsAt:new Date(Date.now()-86400000),expiresAt:new Date(Date.now()+30*86400000)}});await db.settings.create({data:{tenantId:tenant.id,legalName:'Browser Business',address:'Peshawar',phone:'',receiptFooter:'Thank you'}});const branch=await db.branch.create({data:{tenantId:tenant.id,name:'Workspace'}});await db.transaction(tx=>seedRoles(tx,tenant.id));const role=await db.role.findFirst({where:{tenantId:tenant.id,name:'Owner'}});const email=randomUUID()+'@browser.test',password=randomBytes(16).toString('base64url');await db.user.create({data:{tenantId:tenant.id,roleId:role!.id,name:'Owner',email,passwordHash:await bcrypt.hash(password,12),mustChangePassword:false}});await db.currency.create({data:{code:'USD',name:'Dollar',symbol:'$'}});await db.khataPosition.create({data:{tenantId:tenant.id,branchId:branch.id,currencyCode:'USD',quantity:'100',cost:'28000'}});
  const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));const origin='http://127.0.0.1:'+(server.address() as any).port;process.env.APP_ORIGIN=origin;
  const browser=await chromium.launch({executablePath:process.env.KHATA_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});const errors:string[]=[];
  try{
    const pc=await browser.newContext({viewport:{width:1360,height:900},acceptDownloads:true});const phone=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,acceptDownloads:true});const desktop=await pc.newPage(),mobile=await phone.newPage();
    for(const p of [desktop,mobile]){p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.getByLabel('Email').fill(email);await p.getByLabel('Password',{exact:false}).fill(password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.locator('.sync-strip').filter({hasText:'Saved to cloud'}).waitFor({timeout:30000});await p.evaluate(()=>navigator.serviceWorker.ready.then(()=>true));await p.waitForFunction(()=>!!navigator.serviceWorker.controller);}
    await pc.setOffline(true);await desktop.reload();await desktop.locator('.sync-strip').filter({hasText:'Offline'}).waitFor();
    async function entry(p:any,mode:'BUY'|'SELL',name:string,quantity:string,rate:string){await p.locator('.khata-header .primary').click();const dialog=p.locator('dialog');if(mode==='BUY')await dialog.getByRole('button',{name:'Buy Currency',exact:true}).click();await dialog.getByRole('button',{name:'New party',exact:true}).click();await dialog.getByLabel('Party Name',{exact:true}).fill(name);await dialog.locator('select').nth(0).selectOption('PASSPORT');await dialog.getByLabel('Identity Number (Optional)',{exact:true}).fill('AB12345');await dialog.locator('select').nth(1).selectOption('USD');await dialog.getByLabel('Currency Amount',{exact:true}).fill(quantity);await dialog.getByLabel(mode==='BUY'?'Purchase Rate (PKR)':'Selling Rate (PKR)',{exact:true}).fill(rate);await dialog.getByRole('button',{name:mode==='BUY'?'Save Purchase & Payment':'Save Sale',exact:true}).click();await dialog.waitFor({state:'hidden'});await p.locator('.sync-strip').filter({hasText:'1 pending'}).waitFor();}
    await entry(desktop,'SELL','Offline Ali','10','290');await desktop.reload();await desktop.locator('.sync-strip').filter({hasText:'1 pending'}).waitFor();await desktop.goto(origin+'/reports?type=PNL');await desktop.locator('.income-statement').waitFor();assert.ok((await desktop.locator('.income-statement').innerText()).includes('100.00'));
    const pdfPromise=desktop.waitForEvent('download');await desktop.locator('.report-exports').getByRole('link',{name:'PDF',exact:true}).click();const pdf=await pdfPromise;assert.equal((await readFile((await pdf.path())!)).subarray(0,4).toString(),'%PDF');
    await desktop.getByRole('button',{name:'Backup & Sync',exact:true}).click();await desktop.getByLabel('Backup password',{exact:true}).fill('browser-backup-password');const backupPromise=desktop.waitForEvent('download');await desktop.getByRole('button',{name:'Download Backup',exact:true}).click();const backup=await backupPromise;const envelope=JSON.parse(await readFile((await backup.path())!,'utf8'));assert.equal(envelope.format,'khata-os-encrypted-backup');assert.ok(!JSON.stringify(envelope).includes('Offline Ali'));await desktop.locator('dialog').getByRole('button',{name:'Close',exact:true}).click();
    await phone.setOffline(true);await mobile.reload();await mobile.locator('.sync-strip').filter({hasText:'Offline'}).waitFor();await entry(mobile,'BUY','Offline Osman','20','280');assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    for(const [context,p] of [[pc,desktop],[phone,mobile]] as any){await context.setOffline(false);await p.locator('.sync-strip').filter({hasText:'1 pending'}).waitFor();await p.getByRole('button',{name:'Backup & Sync',exact:true}).click();await p.getByRole('button',{name:'Save / Sync Now',exact:true}).click();await p.locator('.sync-strip').filter({hasText:'Saved to cloud'}).waitFor({timeout:30000});await p.locator('dialog').getByRole('button',{name:'Close',exact:true}).click();}
    // A new device downloads the complete saved account, including both original offline entries.
    const third=await browser.newContext(),newPage=await third.newPage();await newPage.goto(origin);await newPage.getByLabel('Email').fill(email);await newPage.getByLabel('Password',{exact:false}).fill(password);await newPage.getByRole('button',{name:'Sign in',exact:true}).click();await newPage.locator('.sync-strip').filter({hasText:'Saved to cloud'}).waitFor({timeout:30000});await newPage.goto(origin+'/parties');await newPage.locator('.party-card').filter({hasText:'Offline Ali'}).first().waitFor();await newPage.locator('.party-card').filter({hasText:'Offline Osman'}).first().waitFor();const pos=await db.khataPosition.findFirst({where:{tenantId:tenant.id}});assert.equal(pos!.quantity,'110');assert.equal(await db.khataEntry.count({where:{tenantId:tenant.id}}),2);assert.deepEqual(errors,[]);await pc.close();await phone.close();await third.close();
  }finally{await browser.close();await new Promise(r=>server.close(r));await db.close();}
});
