import {test, before, after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile, mkdtemp, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import supertest from 'supertest';
import {build} from 'esbuild';
import {indexedDB} from 'fake-indexeddb';
const uri=new URL(process.env.TEST_MONGODB_URI!);uri.pathname='/offline_'+randomUUID().replaceAll('-','');process.env.MONGODB_URI=uri.toString();
const {db,seedRoles,hash,token}=await import('../src/core.js');
const {initializeDatabase}=await import('../src/database.js');
const {app}=await import('../src/index.js');
const {runLocal,setFonts}=await import('../../frontend/public/offline-engine.js');
const request=supertest(app);let first:any,second:any,branch:any,party:any,server:any,origin:string,cookie:string,offline=false,controller:any,temp:string;
async function account(){const tenant=await db.tenant.create({data:{name:'Sync Test'}});await db.subscription.create({data:{tenantId:tenant.id,plan:'Test',startsAt:new Date(Date.now()-86400000*10),expiresAt:new Date(Date.now()+86400000*30)}});await db.settings.create({data:{tenantId:tenant.id,legalName:'Sync Business',address:'Peshawar',phone:'',receiptFooter:'Thank you'}});const b=await db.branch.create({data:{tenantId:tenant.id,name:'Workspace'}});await db.transaction(tx=>seedRoles(tx,tenant.id));const role=await db.role.findFirst({where:{tenantId:tenant.id,name:'Owner'}});const user=await db.user.create({data:{tenantId:tenant.id,roleId:role!.id,name:'Owner',email:randomUUID()+'@sync.test',passwordHash:'not-login',mustChangePassword:false}});const raw=token(),csrf=token();await db.authSession.create({data:{userId:user.id,tokenHash:hash(raw),csrf,expiresAt:new Date(Date.now()+86400000)}});return {tenant,b,user,cookie:'exchange_session='+raw,csrf};}
const post=(route:string,body:any,who=first,key=randomUUID(),at?:string,target?:string)=>{let r=request.post('/api'+route).set('Cookie',who.cookie).set('Origin','http://localhost:5174').set('X-CSRF-Token',who.csrf).set('Idempotency-Key',key);if(at)r=r.set('X-Offline-Created-At',at).set('X-Offline-Account',target||who.tenant.id+':'+who.user.id);return r.send(body);};
async function snapshot(who=first){const r=await request.get('/api/sync/snapshot').set('Cookie',who.cookie);assert.equal(r.status,200);return r.body;}
before(async()=>{await initializeDatabase(db);first=await account();second=await account();branch=first.b;await db.currency.create({data:{code:'USD',name:'Dollar',symbol:'$'}});const p=await post('/parties',{name:'Ali'});party=p.body;assert.equal(p.status,201);assert.equal((await post('/stock',{currencyCode:'USD',quantity:'100',rate:'280'})).status,201);});
after(async()=>{if(server)await new Promise(r=>server.close(r));await db.close();if(temp)await rm(temp,{recursive:true,force:true});});
test('snapshot includes all scoped business records and never credentials, sessions or another tenant',async()=>{const s=await snapshot();assert.equal(s.tenantId,first.tenant.id);assert.ok(s.rows.customer.some((p:any)=>p.id===party.id));for(const rows of Object.values(s.rows) as any[])for(const r of rows)if(r.tenantId)assert.equal(r.tenantId,first.tenant.id);const json=JSON.stringify(s);assert.ok(!json.includes('passwordHash'));assert.ok(!json.includes('tokenHash'));assert.ok(!json.includes(second.tenant.id));});
test('offline engine reuses buy/sell, weighted cost, payments, reversals and separated report handlers',async()=>{let s=await snapshot();const actor=s.actor;const buy=await runLocal(s,actor,'/buy','POST',{partyId:party.id,currencyCode:'USD',quantity:'100',rate:'300'},randomUUID());s={...s,rows:buy.rows};assert.equal(buy.data.cashDelta,'-30000.00');const sale=await runLocal(s,actor,'/give','POST',{partyId:party.id,currencyCode:'USD',quantity:'50',quotedRate:'290',saleRate:'310',paymentMode:'CREDIT'},randomUUID());s={...s,rows:sale.rows};assert.equal(sale.data.pkrDelta,'15500.00');assert.equal(sale.data.realizedProfit,'1000.00');const pnl=(await runLocal(s,actor,'/reports?type=PNL')).data;assert.equal(pnl.summary.netProfit,'1000.00');assert.equal(pnl.rows.length,0);const inv=(await runLocal(s,actor,'/reports?type=POSITION')).data;assert.equal(inv.rows[0].quantity,'150.0000');assert.ok(!('sales' in inv.summary));assert.equal((await runLocal(s,actor,'/reports?type=PURCHASE')).data.rows.length,1);assert.equal((await runLocal(s,actor,'/reports?type=SALE')).data.rows.length,1);const reverse=await runLocal(s,actor,`/entries/${sale.data.id}/reverse`,'POST',{reason:'Offline correction'},randomUUID());s={...s,rows:reverse.rows};assert.equal((await runLocal(s,actor,'/reports?type=PNL')).data.summary.netProfit,'0.00');assert.equal((await runLocal(s,actor,'/parties/'+party.id)).data.balance,'0.00');});
test('failed offline sale rolls back inline customer, stock, ledger and audit together',async()=>{const s=await snapshot(),original=JSON.stringify(s);await assert.rejects(runLocal(s,s.actor,'/give','POST',{newParty:{name:'Not Saved'},currencyCode:'USD',quantity:'101',quotedRate:'280'},randomUUID()),/Not enough/);assert.equal(JSON.stringify(s),original);const view=(await runLocal(s,s.actor,'/parties')).data;assert.ok(!view.rows.some((r:any)=>r.name==='Not Saved'));});
test('two offline devices cannot overdraw the authoritative stock on sync',async()=>{const s=await snapshot(),body={partyId:party.id,currencyCode:'USD',quantity:'60',quotedRate:'280',saleRate:'290',paymentMode:'CASH'},at=new Date(Date.now()-86400000*2).toISOString();const key1=randomUUID(),key2=randomUUID();const a=await runLocal(s,s.actor,'/give','POST',body,key1,at),b=await runLocal(s,s.actor,'/give','POST',body,key2,at);assert.equal(a.rows.khataPosition[0].quantity,'40.0000');assert.equal(b.rows.khataPosition[0].quantity,'40.0000');const accepted=await post('/give',body,first,key1,at);assert.equal(accepted.status,201);assert.equal(accepted.body.reference,a.data.reference);assert.equal(accepted.body.createdAt,at);assert.equal((await post('/give',body,first,key2,at)).status,409);assert.equal((await snapshot()).rows.khataPosition[0].quantity,'40');const retry=await post('/give',body,first,key1,at);assert.equal(retry.body.id,accepted.body.id);assert.equal((await snapshot()).rows.khataPosition[0].quantity,'40');});
test('sync has account guard and customer creation is retry-safe',async()=>{const target=first.tenant.id+':'+first.user.id,at=new Date().toISOString();assert.equal((await post('/stock',{currencyCode:'USD',quantity:'1',rate:'280'},second,randomUUID(),at,target)).status,403);const key=randomUUID(),body={name:'Retry Party'};const a=await post('/parties',body,first,key,at),b=await post('/parties',body,first,key,at);assert.equal(a.status,201);assert.equal(a.body.id,b.body.id);assert.equal((await post('/parties',{name:'Different Party'},first,key,at)).status,409);assert.ok((await snapshot()).completedOperations.some((o:any)=>o.key===key));});
test('offline PDF and Excel use the existing templates and real document formats',async()=>{const s=await snapshot();setFonts((await readFile('assets/fonts/Regular.ttf')).buffer.slice(0),(await readFile('assets/fonts/Bold.ttf')).buffer.slice(0));const pdf=await runLocal(s,s.actor,'/reports/export?type=POSITION');assert.equal(Buffer.from(pdf.bytes).subarray(0,4).toString(),'%PDF');const xlsx=await runLocal(s,s.actor,'/cash/export?format=xlsx');assert.equal(Buffer.from(xlsx.bytes).subarray(0,2).toString(),'PK');});
test('encrypted device queue survives reload, syncs without duplicate writes and supports account-bound backups',async()=>{
  server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));origin='http://127.0.0.1:'+server.address().port;process.env.APP_ORIGIN=origin;cookie=first.cookie;
  temp=await mkdtemp(path.join(tmpdir(),'khata-offline-'));const source=await readFile('../frontend/src/offline.ts','utf8');const engineUrl=pathToFileURL(path.resolve('../frontend/public/offline-engine.js')).href;
  await build({stdin:{contents:source.replace('const url="/offline-engine.js"','const url='+JSON.stringify(engineUrl)),resolveDir:path.resolve('../frontend/src'),loader:'ts'},outfile:path.join(temp,'controller.mjs'),bundle:true,platform:'node',format:'esm',target:'es2022'});
  const nativeFetch=globalThis.fetch;Object.defineProperty(globalThis,'navigator',{value:{onLine:true,storage:{persist:async()=>true}},configurable:true});Object.assign(globalThis,{indexedDB,window:new EventTarget(),BroadcastChannel:undefined});(globalThis as any).window.confirm=()=>true;
  globalThis.fetch=async (url:any,options:any={})=>{if(offline)throw new TypeError('Network offline');return nativeFetch(new URL(url,origin),{...options,headers:{...options.headers,Cookie:cookie,Origin:origin}});};
  controller=await import(pathToFileURL(path.join(temp,'controller.mjs')).href);const identity=(await nativeFetch(origin+'/api/auth/me',{headers:{Cookie:cookie}}).then(r=>r.json())) as any;await controller.activate(identity.user);
  offline=true;(navigator as any).onLine=false;
  const key=randomUUID();const result=await controller.localRequest('/buy','POST',{newParty:{name:'Offline Customer',identityType:'CNIC',identityNo:'123'},currencyCode:'USD',quantity:'10',rate:'280'},key);
  const saved=await controller.deviceState();assert.equal(saved.queue.length,1);assert.equal(saved.view.rows.customer.find((p:any)=>p.id===result.partyId).identityNo,'123');assert.equal((await snapshot()).rows.khataPosition[0].quantity,'40');
  const backup=await controller.exportBackup('backup-test-password');assert.ok(!(await backup.text()).includes('Offline Customer'));const tx=indexedDB.open('khata-os-offline',1);const idb=await new Promise<any>((r,j)=>{tx.onsuccess=()=>r(tx.result);tx.onerror=()=>j(tx.error);});const encrypted=await new Promise<any>(r=>{const q=idb.transaction('kv').objectStore('kv').get('state:'+saved.account);q.onsuccess=()=>r(q.result);});assert.ok(encrypted.bytes instanceof ArrayBuffer);assert.ok(!Buffer.from(encrypted.bytes).toString().includes('Offline Customer'));idb.close();
  // Fresh module instance reads the durable state, not an in-memory optimistic cache.
  const reloaded=await import(pathToFileURL(path.join(temp,'controller.mjs')).href+'?reload=1');assert.equal((await reloaded.deviceState()).queue.length,1);
  const failures=await Promise.allSettled([reloaded.localRequest('/give','POST',{partyId:party.id,currencyCode:'USD',quantity:'30',quotedRate:'280',saleRate:'290'},randomUUID()),reloaded.localRequest('/give','POST',{partyId:party.id,currencyCode:'USD',quantity:'30',quotedRate:'280',saleRate:'290'},randomUUID())]);assert.equal(failures.filter(x=>x.status==='fulfilled').length,1);
  offline=false;(navigator as any).onLine=true;await reloaded.syncNow();assert.equal((await reloaded.deviceState()).queue.length,0);const cloud=await snapshot();assert.equal(cloud.rows.khataPosition[0].quantity,'20');assert.ok(cloud.rows.customer.some((p:any)=>p.name==='Offline Customer'));
  await reloaded.restoreBackup(new File([backup],'backup.json'),'backup-test-password');assert.equal((await reloaded.deviceState()).queue.length,0);assert.equal((await snapshot()).rows.khataPosition[0].quantity,'20');
  await assert.rejects(reloaded.restoreBackup(new File([backup],'backup.json'),'wrong-password-value'),/Wrong backup/);
  cookie=second.cookie;const other=(await nativeFetch(origin+'/api/auth/me',{headers:{Cookie:cookie}}).then(r=>r.json())) as any;await reloaded.activate(other.user);await assert.rejects(reloaded.restoreBackup(new File([backup],'backup.json'),'backup-test-password'),/different account/);
  globalThis.fetch=nativeFetch;
});
